=== giovanni-angeli/pyjamapeople/doc/CRx_SW_formula_file_template.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "version": {
      "type": "string"
    },
    "system": {
      "type": "string"
    },
    "meta": {
      "type": "object",
      "properties": {
        "Brand": {
          "type": "string"
        },
        "Region": {
          "type": "string"
        },
        "Colour code": {
          "type": "string"
        },
        "Variant": {
          "type": "string"
        },
        "Colour name": {
          "type": "string"
        },
        "Second-name": {
          "type": "string"
        },
        "Year": {
          "type": "string"
        },
        "Remark": {
          "type": "string"
        },
        "Quality": {
          "type": "string"
        },
        "Undercoat": {
          "type": "string"
        },
        "Pictograms": {
          "type": "string"
        },
        "Mutation date": {
          "type": "string"
        },
        "Quantity": {
          "type": "string"
        },
        "Cumulative": {
          "type": "string"
        },
        "extra_info": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "required": []
    },
    "ingredients": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "pigment_name": {
            "type": "string"
          },
          "weight(g)": {
            "type": "number"
          },
          "description": {
            "type": "string"
          }
        },
        "required": [
          "pigment_name",
          "weight(g)"
        ]
      }
    }
  },
  "required": [
    "version",
    "system",
    "meta",
    "ingredients"
  ]
}

=== giovanni-angeli/pyjamapeople/doc/CRx_SW_formula_file_template.json
{
  "version": "0.0.1",
  "system": "COINS",
  "meta": {
    "Brand": "UC     UNDERCOAT",
    "Region": "",
    "Colour code": "GS905",
    "Variant": "",
    "Colour name": "GREY SHADE: LIGHT GREY",
    "Second-name": "",
    "Year": "/",
    "Remark": "HSS 2",
    "Quality": "Octobase Eco Plus",
    "Undercoat": "",
    "Pictograms": "",
    "Mutation date": "16-06-2021",
    "Quantity": "1,10 Litro",
    "Cumulative": "No",
    "extra_info": [
      "Octoral Information Services - COINS",
      "Data 19-10-2021 [11:56]",
      "Overview: Formula",
      "COV [gr/l]: 275,2",
      "We strongly advise you to check the colour before use, for many reasons the car colour can be slightly different than the mixed colour."
    ]
  },
  "ingredients": [
    {
      "pigment_name": "W46",
      "weight(g)": 69.9,
      "description": "TN11-W0PR-J00M-1YWC"
    },
    {
      "pigment_name": "W47",
      "weight(g)": 44.4,
      "description": "G721-F0HH-Q003-PCYT"
    },
    {
      "pigment_name": "W48",
      "weight(g)": 26.4,
      "description": "1T11-X02J-500M-CP2G"
    },
    {
      "pigment_name": "W50",
      "weight(g)": 20.0,
      "description": "QG21-Y0KQ-M00K-NDR0"
    },
    {
      "pigment_name": "W909",
      "weight(g)": 5.6,
      "description": "W909"
    },
    {
      "pigment_name": "W60",
      "weight(g)": 0.9,
      "description": "-"
    },
    {
      "pigment_name": "TW80",
      "weight(g)": 19.5,
      "description": "-"
    }
  ]
}
